# Generated by Django 5.2.17 on 2026-10-05 02:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo_audio', models.CharField(max_length=200)),
                ('ruta_audio_original', models.FileField(upload_to='audios/in/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('EXITO', 'Exito'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('harmonic_score', models.FloatField(blank=True, null=True)),
                ('ruta_archivo_pdf', models.FileField(blank=True, null=True, upload_to='audios/pdf/')),
                ('ruta_archivo_mxl', models.FileField(blank=True, null=True, upload_to='audios/mxl/')),
                ('detalles_error', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
